"""
Donation data models.

DonationConfig is the runtime configuration; FundingInfo is the serializable
struct that gets embedded into SkillManifest.funding and SKILL.md frontmatter.
"""

from __future__ import annotations

import os
from dataclasses import dataclass, field, asdict
from typing import Any, Dict, List, Optional


@dataclass
class DonationConfig:
    """Runtime donation configuration, loadable from env vars."""
    enabled: bool = True
    paypal_username: str = "mrstanton81"
    paypal_link: str = "https://paypal.me/mrstanton81"
    suggested_amounts: List[Dict[str, Any]] = field(default_factory=lambda: [
        {"amount": 1.00, "currency": "USD", "label": "Coffee"},
        {"amount": 5.00, "currency": "USD", "label": "Supporter"},
        {"amount": 20.00, "currency": "USD", "label": "Patron"},
    ])
    project_name: str = "ESASS"
    project_url: str = "https://github.com/MN88/esass"
    show_on_activation: bool = True
    show_in_metadata: bool = True
    message_template: str = (
        "This skill was generated by {project}. "
        "If you find it useful, consider supporting the project: {paypal_link}"
    )

    @classmethod
    def from_env(cls) -> "DonationConfig":
        """Create config from environment variables."""
        enabled_raw = os.environ.get("ESASS_DONATION_ENABLED", "true")
        return cls(
            enabled=enabled_raw.lower() == "true",
            paypal_username=os.environ.get("ESASS_PAYPAL_USERNAME", "mrstanton81"),
            paypal_link=os.environ.get("ESASS_PAYPAL_LINK", "https://paypal.me/mrstanton81"),
            project_name=os.environ.get("ESASS_PROJECT_NAME", "ESASS"),
            project_url=os.environ.get("ESASS_PROJECT_URL", "https://github.com/MN88/esass"),
        )

    def render_message(self) -> str:
        """Render the donation message from template."""
        return self.message_template.format(
            project=self.project_name,
            paypal_link=self.paypal_link,
        )


@dataclass
class FundingInfo:
    """
    Serializable funding block embedded in SkillManifest.funding
    and SKILL.md frontmatter.
    """
    paypal: str = "https://paypal.me/mrstanton81"
    suggested_amounts: List[Dict[str, Any]] = field(default_factory=lambda: [
        {"amount": 1.00, "currency": "USD", "label": "Coffee"},
        {"amount": 5.00, "currency": "USD", "label": "Supporter"},
        {"amount": 20.00, "currency": "USD", "label": "Patron"},
    ])
    project: str = "ESASS"
    project_url: str = "https://github.com/MN88/esass"
    message: str = (
        "This skill was generated by ESASS. "
        "If you find it useful, consider supporting the project: https://paypal.me/mrstanton81"
    )

    @classmethod
    def from_config(cls, config: DonationConfig) -> "FundingInfo":
        """Build FundingInfo from a DonationConfig."""
        return cls(
            paypal=config.paypal_link,
            suggested_amounts=config.suggested_amounts,
            project=config.project_name,
            project_url=config.project_url,
            message=config.render_message(),
        )

    def to_dict(self) -> Dict[str, Any]:
        """Serialize to dictionary (for JSON / YAML embedding)."""
        return asdict(self)

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "FundingInfo":
        """Deserialize from dictionary."""
        return cls(**{k: v for k, v in data.items() if k in {
            "paypal", "suggested_amounts", "project", "project_url", "message",
        }})
