"""
Configuration Management for ESASS × OpenClaw Integration

Includes donation and tracing configuration alongside original settings.
"""

import os
from dataclasses import dataclass, field
from pathlib import Path
from typing import List, Optional


@dataclass
class ESASSConfig:
    """ESASS observation and analysis settings."""
    enabled: bool = True
    data_dir: str = "./data/esass"
    sample_rate: float = 1.0

    # Probes
    tool_probe_enabled: bool = True
    reasoning_probe_enabled: bool = True
    decision_probe_enabled: bool = True

    # Pipeline
    buffer_size: int = 100
    flush_interval_seconds: float = 5.0


@dataclass
class OpenClawConfig:
    """OpenClaw integration settings."""
    workspace_dir: str = str(Path.home() / ".openclaw")
    skills_dir: str = "skills"
    config_file: str = "openclaw.json"

    # Gateway
    gateway_url: str = "ws://127.0.0.1:18789"
    gateway_token: Optional[str] = None


@dataclass
class ClawHubConfig:
    """ClawHub registry settings."""
    registry_url: str = "https://clawhub.com"
    token: Optional[str] = None

    # Publishing
    auto_bump: str = "patch"
    default_tags: List[str] = field(default_factory=lambda: ["latest", "esass-generated"])


@dataclass
class LoopSettings:
    """Recursive loop timing and thresholds."""
    # Timing
    observation_window_hours: int = 24
    cycle_interval_hours: int = 6

    # Detection thresholds
    min_events_for_detection: int = 100
    min_support: int = 10
    min_confidence: float = 0.8
    min_stability_days: int = 7

    # Generation
    auto_generate: bool = True
    max_skills_per_cycle: int = 5

    # Publishing
    auto_publish: bool = True
    publish_confidence_threshold: float = 0.85
    publish_support_threshold: int = 15

    # Safety
    require_human_approval: bool = False
    rate_limit_skills_per_day: int = 10


@dataclass
class DonationSettings:
    """Donation / funding configuration."""
    enabled: bool = True
    paypal_username: str = "mrstanton81"
    paypal_link: str = "https://paypal.me/mrstanton81"
    paypal_crypto_enabled: bool = True
    paypal_crypto_link: str = "https://paypal.me/mrstanton81"
    suggested_amounts: List[dict] = field(default_factory=lambda: [
        {"amount": 1.00, "currency": "USD", "label": "Coffee"},
        {"amount": 5.00, "currency": "USD", "label": "Supporter"},
        {"amount": 20.00, "currency": "USD", "label": "Patron"},
    ])
    project_name: str = "ESASS"
    project_url: str = "https://github.com/MN88/esass"
    show_on_activation: bool = True
    show_in_metadata: bool = True
    message_template: str = (
        "This skill was generated by {project}. "
        "If you find it useful, consider supporting the project: {paypal_link} "
        "(crypto accepted via PayPal)"
    )

    @classmethod
    def from_env(cls) -> "DonationSettings":
        """Load donation settings from environment variables."""
        enabled_raw = os.environ.get("ESASS_DONATION_ENABLED", "true")
        paypal_link = os.environ.get("ESASS_PAYPAL_LINK", "https://paypal.me/mrstanton81")
        crypto_raw = os.environ.get("ESASS_PAYPAL_CRYPTO_ENABLED", "true")
        return cls(
            enabled=enabled_raw.lower() == "true",
            paypal_username=os.environ.get("ESASS_PAYPAL_USERNAME", "mrstanton81"),
            paypal_link=paypal_link,
            paypal_crypto_enabled=crypto_raw.lower() == "true",
            paypal_crypto_link=os.environ.get("ESASS_PAYPAL_CRYPTO_LINK", paypal_link),
            project_name=os.environ.get("ESASS_PROJECT_NAME", "ESASS"),
            project_url=os.environ.get("ESASS_PROJECT_URL", "https://github.com/MN88/esass"),
            show_on_activation=os.environ.get(
                "ESASS_DONATION_SHOW_ON_ACTIVATION", "true"
            ).lower() == "true",
            show_in_metadata=os.environ.get(
                "ESASS_DONATION_SHOW_IN_METADATA", "true"
            ).lower() == "true",
        )


@dataclass
class LocalLLMConfig:
    """Local LLM integration settings for cost-optimized skill execution."""
    enabled: bool = True

    # Ollama settings (Tier 1 - Free)
    ollama_endpoint: str = "http://localhost:11434"
    ollama_model: str = "functiongemma"
    ollama_timeout_seconds: int = 30

    # HuggingFace settings (Tier 2 - Cheap fallback)
    hf_model: str = "mistralai/Mistral-7B-Instruct-v0.3"
    hf_token: Optional[str] = None
    hf_timeout_seconds: int = 60

    # Routing settings
    enable_pattern_analysis: bool = True
    enable_skill_naming: bool = True
    enable_semantic_clustering: bool = True
    max_local_tokens: int = 2048
    fallback_on_error: bool = True

    # Task routing (capability -> local suitability score)
    # Higher score = more suitable for local execution
    capability_scores: dict = field(default_factory=lambda: {
        "tool_orchestration": 0.9,
        "file_operations": 0.95,
        "git_operations": 0.8,
        "testing": 0.85,
        "documentation": 0.9,
        "problem_analysis": 0.7,
        "decision_making": 0.6,
        "security": 0.1,  # Keep on Claude
    })

    @classmethod
    def from_env(cls) -> "LocalLLMConfig":
        """Load local LLM settings from environment variables."""
        return cls(
            enabled=os.environ.get("LOCAL_LLM_ENABLED", "true").lower() == "true",
            ollama_endpoint=os.environ.get("OLLAMA_ENDPOINT", "http://localhost:11434"),
            ollama_model=os.environ.get("OLLAMA_MODEL", "functiongemma"),
            ollama_timeout_seconds=int(os.environ.get("OLLAMA_TIMEOUT", "30")),
            hf_model=os.environ.get("HF_MODEL", "mistralai/Mistral-7B-Instruct-v0.3"),
            hf_token=os.environ.get("HF_TOKEN"),
            hf_timeout_seconds=int(os.environ.get("HF_TIMEOUT", "60")),
            enable_pattern_analysis=os.environ.get(
                "LOCAL_LLM_PATTERN_ANALYSIS", "true"
            ).lower() == "true",
            enable_skill_naming=os.environ.get(
                "LOCAL_LLM_SKILL_NAMING", "true"
            ).lower() == "true",
            enable_semantic_clustering=os.environ.get(
                "LOCAL_LLM_SEMANTIC_CLUSTERING", "true"
            ).lower() == "true",
        )


@dataclass
class TracingSettings:
    """Tracing / analytics configuration."""
    enabled: bool = True
    data_dir: str = "./data/esass/tracing"
    anonymize_users: bool = True
    usage_retention_days: int = 90
    evolution_retention_days: int = 365

    @classmethod
    def from_env(cls) -> "TracingSettings":
        """Load tracing settings from environment variables."""
        return cls(
            enabled=os.environ.get("ESASS_TRACING_ENABLED", "true").lower() == "true",
            data_dir=os.environ.get("ESASS_TRACING_DIR", "./data/esass/tracing"),
            anonymize_users=os.environ.get(
                "ESASS_TRACING_ANONYMIZE", "true"
            ).lower() == "true",
            usage_retention_days=int(
                os.environ.get("ESASS_TRACING_USAGE_RETENTION_DAYS", "90")
            ),
            evolution_retention_days=int(
                os.environ.get("ESASS_TRACING_EVOLUTION_RETENTION_DAYS", "365")
            ),
        )


@dataclass
class IntegrationConfig:
    """Complete integration configuration."""
    esass: ESASSConfig = field(default_factory=ESASSConfig)
    openclaw: OpenClawConfig = field(default_factory=OpenClawConfig)
    clawhub: ClawHubConfig = field(default_factory=ClawHubConfig)
    loop: LoopSettings = field(default_factory=LoopSettings)
    donation: DonationSettings = field(default_factory=DonationSettings)
    tracing: TracingSettings = field(default_factory=TracingSettings)
    local_llm: LocalLLMConfig = field(default_factory=LocalLLMConfig)

    @classmethod
    def from_env(cls) -> "IntegrationConfig":
        """Load configuration from environment variables."""
        return cls(
            esass=ESASSConfig(
                enabled=os.environ.get("ESASS_ENABLED", "true").lower() == "true",
                data_dir=os.environ.get("ESASS_DATA_DIR", "./data/esass"),
                sample_rate=float(os.environ.get("ESASS_SAMPLE_RATE", "1.0")),
            ),
            openclaw=OpenClawConfig(
                workspace_dir=os.environ.get(
                    "OPENCLAW_WORKSPACE",
                    str(Path.home() / ".openclaw"),
                ),
                gateway_url=os.environ.get(
                    "OPENCLAW_GATEWAY_URL",
                    "ws://127.0.0.1:18789",
                ),
                gateway_token=os.environ.get("OPENCLAW_GATEWAY_TOKEN"),
            ),
            clawhub=ClawHubConfig(
                registry_url=os.environ.get("CLAWHUB_REGISTRY", "https://clawhub.com"),
                token=os.environ.get("CLAWHUB_TOKEN"),
            ),
            loop=LoopSettings(
                observation_window_hours=int(
                    os.environ.get("LOOP_OBSERVATION_HOURS", "24")
                ),
                cycle_interval_hours=int(
                    os.environ.get("LOOP_CYCLE_HOURS", "6")
                ),
                auto_publish=os.environ.get(
                    "LOOP_AUTO_PUBLISH", "true"
                ).lower() == "true",
            ),
            donation=DonationSettings.from_env(),
            tracing=TracingSettings.from_env(),
            local_llm=LocalLLMConfig.from_env(),
        )


# Global configuration instance
_config: Optional[IntegrationConfig] = None


def get_config() -> IntegrationConfig:
    """Get global configuration."""
    global _config
    if _config is None:
        _config = IntegrationConfig.from_env()
    return _config


def set_config(config: IntegrationConfig) -> None:
    """Set global configuration."""
    global _config
    _config = config
