"""
ESASS Skill → Claude Project Skill Formatter.

Transforms ESASS SkillManifest objects into .claude-compatible SKILL.md files.
"""

from datetime import datetime
from pathlib import Path
from typing import List, Optional, Dict, Any

from esass.models import SkillManifest, PatternDefinition


class ClaudeSkillFormatter:
    """Converts ESASS skills to .claude/skills/ SKILL.md format."""

    def __init__(self, output_dir: str = ".claude/skills"):
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def format_skill(
        self,
        manifest: SkillManifest,
        pattern: Optional[PatternDefinition] = None,
    ) -> str:
        """Convert SkillManifest to SKILL.md content."""

        # Frontmatter
        frontmatter = {
            "name": manifest.name.replace("_", "-").lower(),
            "description": manifest.description,
            "version": manifest.version,
            "genesis": {
                "type": manifest.genesis_type,
                "confidence": round(pattern.confidence, 2) if pattern else 0.9,
                "support": pattern.support if pattern else 0,
                "date": manifest.created_at,
            },
            "triggers": manifest.triggers,
            "capabilities": list(manifest.capabilities),
        }

        import yaml

        yaml_fm = yaml.dump(frontmatter, sort_keys=False)

        # Body
        body = f"""# {manifest.name.replace("_", " ").title()}

## Overview
{manifest.description}

## Workflow
{manifest.implementation_summary}

## Triggers
{chr(10).join([f"- {t}" for t in manifest.triggers])}

## Capabilities
{chr(10).join([f"- {c}" for c in manifest.capabilities])}

---
*Generated by ESASS Genesis Engine on {datetime.now().isoformat()}*
"""
        return f"---\n{yaml_fm}---\n\n{body}"

    def save_skill(
        self,
        manifest: SkillManifest,
        pattern: Optional[PatternDefinition] = None,
    ) -> Path:
        """Save skill to filesystem."""
        content = self.format_skill(manifest, pattern)
        safe_name = manifest.name.replace("_", "-").lower()

        # In .claude/skills, usually each skill is its own file or directory
        skill_dir = self.output_dir / safe_name
        skill_dir.mkdir(parents=True, exist_ok=True)
        skill_file = skill_dir / "SKILL.md"
        skill_file.write_text(content, encoding="utf-8")
        return skill_file

    def batch_convert(
        self,
        manifests: List[SkillManifest],
        patterns: Optional[Dict[str, PatternDefinition]] = None,
    ) -> List[Path]:
        """Convert multiple skills."""
        patterns = patterns or {}
        saved: List[Path] = []
        for manifest in manifests:
            pattern = None
            if manifest.source_pattern_ids:
                pattern = patterns.get(manifest.source_pattern_ids[0])
            saved.append(self.save_skill(manifest, pattern))
        return saved
